### ISSUE TITLE
Codecademy.com does not support the installed IceWeasel browser

### ISSUE THREAD

**Issue by madebydavid** [pablobm/w2c3-livecd#3]
Would be awesome if we could have Chromium also installed?

**Comment by pablobm** [comment]
Darn. I'd rather having only one to minimise friction, but if there's no other option, I'll add Chrome/Chromium too.

I'm going to see if Debian offers Firefox 45 which, as the latest [ESR version](https://www.mozilla.org/en-US/firefox/organizations/faq/), I expect will be what Codecademy requires. If that doesn't work, I'll give up and install Chromium too.

**Comment by pablobm** [comment]
It would appear I can install Firefox 45. I'll try this and install it in some laptops when I can; see if that helps. In the mean time, I've asked Codecademy about this on Twitter: https://twitter.com/pablobm/status/751848199355236356

Also, TIL that Debian have finally reached an agreement with Mozilla, marking [the end of the Iceweasel age](https://lwn.net/Articles/676799/)
